"""Price snapshots (price history per product, retailer and currency).

Revision ID: 0010
Revises: 0009
Create Date: 2026-10-01 02:47:17.013403+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0010"
down_revision: str | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "price_snapshots",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("variant_id", sa.Uuid(), nullable=True),
        sa.Column("retailer", sa.String(length=100), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("in_stock", sa.Boolean(), nullable=True),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f("ck_price_snapshots_currency_iso")),
        sa.CheckConstraint(
            "source IN ('MANUAL', 'IMPORT', 'EVIDENCE')",
            name=op.f("ck_price_snapshots_source_valid"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_price_snapshots_amount_positive")),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_price_snapshots_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_price_snapshots_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
            name=op.f("fk_price_snapshots_variant_id_product_variants"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_snapshots")),
        sa.UniqueConstraint(
            "product_id",
            "retailer",
            "currency",
            "observed_at",
            name=op.f("uq_price_snapshots_product_id_retailer_currency_observed_at"),
        ),
    )
    op.create_index(
        op.f("ix_price_snapshots_created_by_id"), "price_snapshots", ["created_by_id"], unique=False
    )
    op.create_index(
        "ix_price_snapshots_history",
        "price_snapshots",
        ["product_id", "currency", "observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_price_snapshots_variant_id"), "price_snapshots", ["variant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_price_snapshots_variant_id"), table_name="price_snapshots")
    op.drop_index("ix_price_snapshots_history", table_name="price_snapshots")
    op.drop_index(op.f("ix_price_snapshots_created_by_id"), table_name="price_snapshots")
    op.drop_table("price_snapshots")
    # ### end Alembic commands ###
