"""Purchase requirements and immutable requirement versions.

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-30 22:48:48.392348+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "purchase_requirements",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("current_version", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "current_version >= 0", name=op.f("ck_purchase_requirements_current_version_valid")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_purchase_requirements_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["comparison_workspaces.id"],
            name=op.f("fk_purchase_requirements_workspace_id_comparison_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_requirements")),
        sa.UniqueConstraint("workspace_id", name=op.f("uq_purchase_requirements_workspace_id")),
    )
    op.create_index(
        op.f("ix_purchase_requirements_created_by_id"),
        "purchase_requirements",
        ["created_by_id"],
        unique=False,
    )
    op.create_table(
        "requirement_versions",
        sa.Column("requirement_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("spec", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "unparsed", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("extractor", sa.String(length=100), nullable=False),
        sa.Column("change_note", sa.String(length=500), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_requirement_versions_version_valid")),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_requirement_versions_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["purchase_requirements.id"],
            name=op.f("fk_requirement_versions_requirement_id_purchase_requirements"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_versions")),
        sa.UniqueConstraint(
            "requirement_id", "version", name=op.f("uq_requirement_versions_requirement_id_version")
        ),
    )
    op.create_index(
        op.f("ix_requirement_versions_created_by_id"),
        "requirement_versions",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_requirement_versions_requirement_id"),
        "requirement_versions",
        ["requirement_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_requirement_versions_requirement_id"), table_name="requirement_versions")
    op.drop_index(op.f("ix_requirement_versions_created_by_id"), table_name="requirement_versions")
    op.drop_table("requirement_versions")
    op.drop_index(
        op.f("ix_purchase_requirements_created_by_id"), table_name="purchase_requirements"
    )
    op.drop_table("purchase_requirements")
    # ### end Alembic commands ###
