"""sources snapshots documents

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-30 21:37:38.761032+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_sources",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("authority", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("last_ingested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "authority IN ('OFFICIAL', 'THIRD_PARTY', 'USER')",
            name=op.f("ck_product_sources_authority_valid"),
        ),
        sa.CheckConstraint(
            "source_type IN ('MANUFACTURER_PAGE', 'SPECIFICATION_SHEET', 'MANUAL', 'WARRANTY', 'RETURN_POLICY', 'REVIEW', 'USER_DOCUMENT', 'OTHER')",
            name=op.f("ck_product_sources_source_type_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'INGESTED', 'FAILED')",
            name=op.f("ck_product_sources_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_product_sources_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_sources_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["comparison_workspaces.id"],
            name=op.f("fk_product_sources_workspace_id_comparison_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_sources")),
    )
    op.create_index(
        op.f("ix_product_sources_created_by_id"), "product_sources", ["created_by_id"], unique=False
    )
    op.create_index(
        op.f("ix_product_sources_product_id"), "product_sources", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_product_sources_workspace_id"), "product_sources", ["workspace_id"], unique=False
    )
    op.create_table(
        "source_snapshots",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("raw_content", sa.LargeBinary(), nullable=False),
        sa.Column("final_url", sa.String(length=2048), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "byte_size >= 0", name=op.f("ck_source_snapshots_byte_size_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["product_sources.id"],
            name=op.f("fk_source_snapshots_source_id_product_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_snapshots")),
        sa.UniqueConstraint(
            "source_id", "sha256", name=op.f("uq_source_snapshots_source_id_sha256")
        ),
    )
    op.create_index(
        op.f("ix_source_snapshots_last_seen_at"), "source_snapshots", ["last_seen_at"], unique=False
    )
    op.create_index(
        op.f("ix_source_snapshots_source_id"), "source_snapshots", ["source_id"], unique=False
    )
    op.create_table(
        "source_documents",
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("char_count", sa.Integer(), nullable=False),
        sa.Column("parser", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_source_documents_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["source_snapshots.id"],
            name=op.f("fk_source_documents_snapshot_id_source_snapshots"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["product_sources.id"],
            name=op.f("fk_source_documents_source_id_product_sources"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["comparison_workspaces.id"],
            name=op.f("fk_source_documents_workspace_id_comparison_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_documents")),
        sa.UniqueConstraint("snapshot_id", name=op.f("uq_source_documents_snapshot_id")),
    )
    op.create_index(
        op.f("ix_source_documents_product_id"), "source_documents", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_source_documents_source_id"), "source_documents", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_source_documents_workspace_id"), "source_documents", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_source_documents_workspace_id"), table_name="source_documents")
    op.drop_index(op.f("ix_source_documents_source_id"), table_name="source_documents")
    op.drop_index(op.f("ix_source_documents_product_id"), table_name="source_documents")
    op.drop_table("source_documents")
    op.drop_index(op.f("ix_source_snapshots_source_id"), table_name="source_snapshots")
    op.drop_index(op.f("ix_source_snapshots_last_seen_at"), table_name="source_snapshots")
    op.drop_table("source_snapshots")
    op.drop_index(op.f("ix_product_sources_workspace_id"), table_name="product_sources")
    op.drop_index(op.f("ix_product_sources_product_id"), table_name="product_sources")
    op.drop_index(op.f("ix_product_sources_created_by_id"), table_name="product_sources")
    op.drop_table("product_sources")
    # ### end Alembic commands ###
