"""Agent runs (cited output + citation validation per execution).

Revision ID: 0009
Revises: 0008
Create Date: 2026-10-01 00:50:03.961275+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_runs",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("agent", sa.String(length=40), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("evidence_pack_id", sa.Uuid(), nullable=True),
        sa.Column("requirement_version", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("engine", sa.String(length=100), nullable=False),
        sa.Column("degraded", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("validation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.String(length=500), nullable=True),
        sa.Column("duration_ms", sa.Integer(), server_default="0", nullable=False),
        sa.Column("tokens_used", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('SUCCEEDED', 'FAILED')", name=op.f("ck_agent_runs_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_agent_runs_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_pack_id"],
            ["evidence_packs.id"],
            name=op.f("fk_agent_runs_evidence_pack_id_evidence_packs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_agent_runs_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["comparison_workspaces.id"],
            name=op.f("fk_agent_runs_workspace_id_comparison_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    op.create_index(
        op.f("ix_agent_runs_created_by_id"), "agent_runs", ["created_by_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_runs_evidence_pack_id"), "agent_runs", ["evidence_pack_id"], unique=False
    )
    op.create_index(op.f("ix_agent_runs_product_id"), "agent_runs", ["product_id"], unique=False)
    op.create_index(
        "ix_agent_runs_workspace_agent_created",
        "agent_runs",
        ["workspace_id", "agent", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_agent_runs_workspace_agent_created", table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_product_id"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_evidence_pack_id"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_created_by_id"), table_name="agent_runs")
    op.drop_table("agent_runs")
    # ### end Alembic commands ###
