"""Evidence packs and immutable evidence items (citable snapshots).

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-30 23:02:23.123631+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evidence_packs",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("query", sa.String(length=500), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("embedding_model", sa.String(length=100), nullable=True),
        sa.Column("requirement_version", sa.Integer(), nullable=True),
        sa.Column("degraded", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_evidence_packs_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["comparison_workspaces.id"],
            name=op.f("fk_evidence_packs_workspace_id_comparison_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_packs")),
    )
    op.create_index(
        op.f("ix_evidence_packs_created_by_id"), "evidence_packs", ["created_by_id"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_packs_workspace_id"), "evidence_packs", ["workspace_id"], unique=False
    )
    op.create_table(
        "evidence_items",
        sa.Column("pack_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("chunk_id", sa.Uuid(), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("source_title", sa.String(length=300), nullable=False),
        sa.Column("source_url", sa.String(length=2048), nullable=True),
        sa.Column("authority", sa.String(length=16), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("position >= 1", name=op.f("ck_evidence_items_position_valid")),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["document_chunks.id"],
            name=op.f("fk_evidence_items_chunk_id_document_chunks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["pack_id"],
            ["evidence_packs.id"],
            name=op.f("fk_evidence_items_pack_id_evidence_packs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_evidence_items_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["product_sources.id"],
            name=op.f("fk_evidence_items_source_id_product_sources"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_items")),
        sa.UniqueConstraint("pack_id", "position", name=op.f("uq_evidence_items_pack_id_position")),
    )
    op.create_index(
        op.f("ix_evidence_items_chunk_id"), "evidence_items", ["chunk_id"], unique=False
    )
    op.create_index(op.f("ix_evidence_items_pack_id"), "evidence_items", ["pack_id"], unique=False)
    op.create_index(
        op.f("ix_evidence_items_product_id"), "evidence_items", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_items_source_id"), "evidence_items", ["source_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_evidence_items_source_id"), table_name="evidence_items")
    op.drop_index(op.f("ix_evidence_items_product_id"), table_name="evidence_items")
    op.drop_index(op.f("ix_evidence_items_pack_id"), table_name="evidence_items")
    op.drop_index(op.f("ix_evidence_items_chunk_id"), table_name="evidence_items")
    op.drop_table("evidence_items")
    op.drop_index(op.f("ix_evidence_packs_workspace_id"), table_name="evidence_packs")
    op.drop_index(op.f("ix_evidence_packs_created_by_id"), table_name="evidence_packs")
    op.drop_table("evidence_packs")
    # ### end Alembic commands ###
